# Generated by Django 4.1.2 on 2022-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('jerarquia', models.CharField(choices=[('1', 'Presidente'), ('2', 'Gerente General'), ('3', 'Gerente de Área'), ('4', 'Responsable de Área'), ('5', 'Supervisor'), ('6', 'Colaborador')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='departamento',
        ),
    ]
