# Generated by Django 4.1.2 on 2022-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamentos_delete_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='jerarquia',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20),
        ),
    ]
