# Generated by Django 4.1.2 on 2022-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='contribuyente_set',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='hijos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=25),
        ),
    ]
