# Generated by Django 4.1.2 on 2022-10-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_alter_miembro_contribuyente_set_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='miembroModel',
        ),
    ]
