# Generated by Django 4.1.2 on 2022-10-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembro', '0002_alter_miembro_contribuyente_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('fecha_entrega', models.DateField(default='dd/mm/aaaa')),
                ('hora_entrega', models.TimeField(default='hh:mm')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_hour', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembro.miembro')),
            ],
        ),
    ]
