# Generated by Django 4.1.2 on 2022-10-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0003_delete_miembromodel'),
        ('tareas', '0002_alter_tarea_nombre_alter_tarea_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='miembro.miembro'),
        ),
    ]
