# Generated by Django 4.1.2 on 2022-11-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('departamentos', '0003_alter_departamentos_jerarquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('empleado_o_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienteRol', to='clientes.cliente')),
                ('nombre_de_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentoRol', to='departamentos.departamentos')),
            ],
        ),
    ]
