# Generated by Django 4.1.2 on 2022-11-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamentos_jerarquia'),
        ('rubro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='departamentos.departamentos'),
        ),
    ]
