# Generated by Django 4.1.2 on 2022-11-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubro', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('tipo_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nombre_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('titular_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('monto_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='clientes.cliente')),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubro', to='rubro.rubro')),
            ],
        ),
    ]
